title: Website title
description: A short description for the website
theme: just-the-docs

url: https://aFarchi.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
